name: Move Issue to In Progress on Assign

on:
  issues:
    types: [assigned]

permissions:
  issues: write

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CODELAB_STAGING_TOKEN }}   # Substitua pelo seu PAT
          script: |
            const projectNumber = 2;  // Altere se necessário (ver número na URL do projeto)
            const orgName = "CodeLab-Staging";   // Substitua pelo seu nome de usuário ou organização

            // Obter ID do projeto
            const projectQuery = await github.graphql(`
              query($org: String!, $number: Int!) {
                organization(login: $org) {
                  projectV2(number: $number) {
                    id
                    title
                  }
                }
              }
            `, {
              org: orgName,
              number: projectNumber
            });

            const projectId = projectQuery.organization.projectV2.id;
            console.log('✅ Project ID:', projectId);

            // Obter ID da issue
            const issueId = context.payload.issue.node_id;

            // Adicionar issue ao projeto
            const addItemMutation = await github.graphql(`
              mutation($projectId: ID!, $contentId: ID!) {
                addProjectV2ItemById(input: {
                  projectId: $projectId
                  contentId: $contentId
                }) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId: projectId,
              contentId: issueId
            });

            console.log('✅ Issue added to project!');

            // Mover para "In Progress" (usando a API REST para mudar de coluna)
            // Primeiro encontre a coluna "In Progress"
            const columns = await github.rest.projects.listColumns({
              project_id: projectId,
            });

            const inProgressColumn = columns.data.find(c => c.name === "In Progress");
            if (!inProgressColumn) {
              throw new Error('Column "In Progress" not found');
            }

            // Mover a issue para a coluna
            await github.rest.projects.createCard({
              column_id: inProgressColumn.id,
              content_id: issueId,
              content_type: 'Issue',
            });

            console.log('✅ Issue moved to "In Progress"!');