name: Move Issue to In Progress

on:
  issues:
    types: [assigned]

jobs:
  move_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to "In Progress"
        uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: "Nome do seu projeto"      # Nome do Project Board
          column: "In Progress"               # Coluna destino
          repo-token: ${{ secrets.GITHUB_TOKEN }}
