permissions:
  contents: read
  issues: write
  projects: write

jobs:
  move_to_in_progress:
    runs-on: ubuntu-latest
    steps:
      - name: Move issue to In Progress
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.CODELAB_STAGING_TOKEN }}   # << aqui usa seu PAT
          script: |
            const projectNumber = 2;
            const fieldName = "Status";
            const optionName = "In Progress";

            const projectQuery = await github.graphql(`
              query($org: String!, $number: Int!) {
                organization(login: $org) {
                  projectV2(number: $number) {
                    id
                    fields(first: 20) {
                      nodes {
                        ... on ProjectV2FieldCommon {
                          id
                          name
                        }
                        ... on ProjectV2SingleSelectField {
                          id
                          name
                          options {
                            id
                            name
                          }
                        }
                      }
                    }
                  }
                }
              }
            `, {
              org: "CodeLab-Staging",   // fixo para sua organização
              number: projectNumber
            });

            console.log("✅ Projeto encontrado:", projectQuery.organization.projectV2.title);
